.babelrc
package.json

Fixes #105 
Use the standard babel presets to support environments without esmodules support.

Use env babel preset, fixes issues with nextjs and jest

---

docz/examples/09-example-localization.mdx
docz/props.mdx
index.d.ts
src/m-table-body.js
src/m-table-filter-row.js
src/m-table-header.js
src/m-table-pagination.js
src/m-table-toolbar.js
src/material-table.js

Relate the Github issue with this PR using `#113`
added tooltips in toolbar (first, previous, next and last button) and filter row
changed all "direct" texts to values from localization props
added default (english) translation as default props in each component
adjusted docs, examples etc. with the new translation
MaterialTable
MTableToolbar
MTablePagination
MTableHeader
MTableBody
MTableFilterRow
*
I usually develop projects not libraries, so I'm not sure if i.e. the `index.d.ts` file is correct or if the coding style fits (as far as I can see there are more than one), but I run the lint command with no errors or warnings...
Not knowing docz I didn't run any commands regarding docz and in the contribution file you …

added a few tooltips and made component completely translatable

---

src/m-table-cell.js
src/m-table-header.js

See https://material-ui.com/api/table-cell/
#124 
Remove warning about numerin being deprecated for TableCell :
Warning: Failed prop type: The prop `numeric` of `TableCell` is deprecated. Instead, use the `align` property.
in TableCell (created by WithStyles(TableCell))
in WithStyles(TableCell) (created by MTableHeader)
in tr (created by Context.Consumer)
in TableRow (created by WithStyles(TableRow))
in WithStyles(TableRow) (created by MTableHeader)
in thead (created by TableHead)
in TableHead (created by WithStyles(TableHead))
in WithStyles(TableHead) (created by MTableHeader)
in MTableHeader (created by MaterialTable)
in table (created by Table)
in Table (created by WithStyles(Table))
in WithStyles(Table) (created by MaterialTable)
in div (created by MaterialTable)
in div (created by …

Fix react warning about numeric being deprecated

---

src/material-table.js

Relate the Github issue with this PR using `#127`
By using anything else than a string for the icons in the actions prop the console gave a warning, this is now fixed. 
* Element types allowed for icons in the action prop

Fixed error regarding actions/icon #127

---

src/material-table.js

fix the issue #82 in the same time
#96 
#82 
#96 :
* init table with already checked rows
#82 : 
* material-table component will update only if it gets new data (not only new props). That way, if a rows is checked, it won't go through `UNSAFE_componentWillReceiveProps` logic
* material-table.js

feat(checkbox): add init checked rows

---

index.d.ts
package.json
src/material-table.js

#64 
As it stands, the onXyz events are triggered after data has already been loaded. By adding "before" events (and retaining the "after" events), we can easily enable remotely loading data before subsequently acting on it. I've bumped the version number to 1.12 and retained the original event handler names (eg: onChangePage) for backward compatibility (can just easily remove them). I can also add docs. I have a working example with react-redux and saga that remotely loads data from a REST API. Submitting this PR now a bit more bare bones to give you time to take a look and LMK what you think.

add before & after event hooks which fixes material-table/issues/64

---

src/material-table.js

When getFieldValue() is used, check if the data is defined, then fallback to "getbystring" instead of checking if value is "false".
For exemple, if you had an array like this: 
[{"toto.tata": ''}]
it would return null instead of an empty string.
branch | PR
*

Check if value is undefined instead of 'false'

---

src/m-table-body-row.js

If tableData is undefined, this line caused a crash, because tableData.showDetailPanel was called.
This fixes this, because it checks, if table data is present.

Fixes crash, if no tableData provided

---

src/m-table-header.js
src/material-table.js

#216 
Adds logic around draggable headers so that they are only draggable if the grouping option is set to true.
MTableHeader
This is my first pull request.

adds logic around draggable headers based on grouping option

---

src/material-table.js

Issue not opened
Fixes an issue where the field of the object is null (instead of only undefined). This changewill make it not crash, but rather return an undefined value.

Fixes issue with search when parent field is null

---

src/m-table-edit-row.js

This fixes a padding error for the editable row, when the actionsColumIndex is -1:
- m-table-edit-row

Edit padding fix

---

docz/props.mdx
index.d.ts
src/m-table-toolbar.js
src/material-table.js

This PR Closes #288
This PR add the `exportCsv` prop to material table, so the user is able to build it's own csv file.
* `MaterialTable`
* `MTableToolbar `
The solution is pretty much the same as proposed in the issue, I just needed to pass the `m-table-toolbar` so can call the `this.setState` and close the tooltip.
My suggestion would be "hook" the `defaultCsv` and close the tooltip inside the toolbar, so least exposure would be needed, but I'm keeping this PR simple, focused on the solution so we can discuss it better.
Thank youuu!! :D
I tested in my application and worked with the following code:
```jsx
import { CsvBuilder } from 'filefy';
function Index({model}) {
const handleExportCsv = (toolbar, columns, …
```

Add support for default `exportCsv` function.

---

src/m-table-body.js

Without this modification, EditRow incorrectly offsets columns, takes on incorrect data types per field, and clips content inappropriately.
* `MTableEditRow`(seen as `props.components.EditRow` from `MTableBody`)

Correctly pass detailPanel to EditRow.

---

src/m-table-header.js

The properties at the end of the spread notation overwrite any existing properties set by the user through the headerStyle from options or the column itself.
See the "Sort overriding with customSort" example.
https://mbrn.github.io/material-table/#/docz-examples-04-example-sorting
The custom headerStyle backgroundColor for the name column is being overwritten by the white backgroundColor from stickyStyle.

Make sure 'stickyStyle' does not overwrite any user defined styles

---

src/m-table-toolbar.js

#398 
When a column has a lookup feature, than export the values of the lookup, not the keys.
no related PRs
* m-table-toolbar

fix: exportCsv menu closing and lookup columns

---

docz/examples/15-example-editable.mdx
docz/props.mdx
index.d.ts
src/m-table-edit-row.js
src/material-table.js

#350
Allow columns to be flagged as read-only when editing a row. The read-only column remains editable when adding a new row.
* readonly flag added to column definition
* MTableEditRow updated to render column with this.props.components.Cell if readonly and not adding a new row, otherwise behaviour is as before.
* additional example added to "Editable Examples" demonstrating the feature

Add support for read-only columns

---

src/m-table-toolbar.js
src/material-table.js

No current issue.
Hey there. I needed to display the search field to the left, and could not use the component function to recreate the whole thing. Just added the params. Not sure if this is up to your standard I am not that experienced.
I would assume this is a small change/improvement. I also made sure the left padding is removed if no title is showed.
branch | PR
*

Added searchFieldAlignment option

---

docz/props.mdx
index.d.ts
src/m-table-toolbar.js
src/material-table.js

Allow to customize toolbar title.
Toolbar.
It was useful for my application to reuse toolbar space and integrate a "New" record button command to go into a separate detail page.
with follow code
```ts
<MaterialTable
title={""}
customTitle={
<Grid
container={true}
direction="row"
justify="space-around"
alignItems="center"
>
<Grid item={true}>
<Typography variant="h6">
Jobs
</Typography>
</Grid>
<Grid item={true}>
<Button color="primary">New</Button>
</Grid>
</Grid>
}
```
to generate

table toolbar custom title

---

src/m-table-action.js

No related issue
Moved the Icon Button element in the action button so that a custom button can be assigned to the icon option correctly (was returning a nesting error in React since it was nesting the custom button inside the IconButton element).
This is how I am passing it.
```
const AddButton = props => <Button {...props}>Add New Template</Button>;
const actions = [
{
icon: props => AddButton(props),
onClick: (event, rowData) => {
handleOpen("addDialog");
},
iconProps: {
color: "primary"
},
isFreeAction: true
}
];
```
PS sorry for the dual commit, I left prettifier on before editing and I messed up the rollback so I had to re-commit:S
branch | PR
List general components of …

Changed custom action icon object handling

---

index.d.ts
src/m-table-edit-row.js

Custom components should have better TypeScript intellisense, I've done this for editComponent. Will open up a PR for others I find. Need feedback if they should live in this branch or open up seperate small PRs for each component that I come across.
**NOTE**: small fix here, `editComponent` should not receive the function that it's calling, why would the child need to call the function to render more of itself? Fix uses spread operator to pull `editComponent` out, use it and then pass remaining props into cell component.
`N/A`
* index.d.ts - added two interfaces
* m-table-edit-row-js - fixed issue with `editComponent()` being sent in improperly
Loving finding things to help …

fix types for editComponent

---

docz/props.mdx
src/m-table-toolbar.js
src/material-table.js

None
At the moment, material-table's CSV export only exports the data that is currently visible. This change makes it possible to instead export all data by passing `exportAllData: true` in the options.
None
* CSV exporting
material-table is the best batteries-included table package for material UI that we've encountered so far. Thanks for all your hard work!

Add option for exporting all data instead of just the visible rows

---

src/utils/data-manager.js

#494
This PR fixes the small bug I have mentioned in the above issue as far as I have tested. Tree view renders correctly after these checks. Please let me know if I have missed anything.
None
* Tree Data view when table receives `parentChildData` prop
Thank you for your hard work and your contributions to open source world, keep it up please!

Fix TypeError in findDataByPath function when childRows are null

---

index.d.ts

When using typescript and a custom icon is necessary to set all icons or use `as Icons` in this property, which is a bad solution since it'll silent any error in tslint. In `MaterialTable` class, method `getProps` already covers this interface using a spread of `defaultProps.icons`
* index.ts.d

Optional icons interface

---

README.md

Fixes #558 
This was caused by moving all the `.md` files to .github folder
Only the README.md is affected

fix broken link to CONTRIBUTING.md

---

src/components/m-table-body-row.js
src/material-table.js

Feature: Returning the row Data was checked  and it is available in onSelectionChange.
With this extra data you can track the selected check after any filtered and paint again
branch | PR
*

Feature: Returning the row Data was checked 

---

src/material-table.js

#568 
Fixes component crashing for accessing user provided props instead of default ones.
* Main table component

Fixes not using default OverlayLoading component.

---

package.json
src/components/m-table-edit-field.js
src/components/m-table-filter-row.js
src/components/m-table-stepped-pagination.js
src/components/m-table-toolbar.js
src/default-props.js
src/prop-types.js

#619 
Migration to `@material-ui/core` v4  alongside with `material-ui-pickers` v3 (note: the package has been moved to `@material-ui/pickers`)
Changes:
* Add new PropTypes: RefComponent, StyledComponent
* Update theme.spacing.unit usages to a new [API](https://material-ui.com/guides/migration-v3/#theme)
* Wrap icons in React.forwardRef (see [caveat with refs](https://material-ui.com/guides/composition/#caveat-with-refs))

Migrate to MUI v4

---

README.md

#612
Some readme updates to fill in some gaps in docs.
- Updated readme to explain the prerequisites for react since react-beautiful-dnd requires 16.8.5 for hooks support. (I can across this issue when using material-table at first)
- Added details for using material icons instead of the font library to allow for further customisation of material-table
Thanks and been loving material-table!

Update README.md with icon details

---

README.md

Fixed typo in README.md where `material-table` is listed in the icons install through NPM rather than `@material-ui/icons`.

Update README.md to fix @material-ui/icons typo

---

src/material-table.js

Fixes #708 
Change the page if it is out of range from either deleting rows or filtering
N/A
MaterialTable
The error still appears in the console as we don't catch it before the update.
The ideal solution would be to use getDerivedStateFromProps and also use it to replace `UNSAFE_componentWillReceiveProps`. This seemed like quite a major refactor though, so I decided against it

Change page if it is out of range

---

demo/demo.js
src/utils/data-manager.js

#717
Reworked the logic for searching in tree views. With these changes, the following rows are shown:
- all items that match the search, regardless of their level in the tree
- all their parent items, regardless of whether they match the search
- all child items of matched items, in a collapsed state
I consider this an intuitive way to search in a tree. Either a leaf node is the target, or some branch node where I want to be able to explore the deeper structure
the data-manager is getting awfully large. It might benefit from splitting up into search-manager, filter-manager, etc.

fixed tree sort behavior

---

types/index.d.ts

#763 and #732 
This improves the Typescript definitions, by fixing the usage of imports from the React module and by making the data and rowData generic, which improves type safety.

Make rowData generic in Typescript type definitions

---

src/components/m-table-header.js
src/material-table.js

#753
Disable dragging so columns cannot be reordered 
* grouping
Grouping will not work if the draggable option is false, also not sure if I should switch components where dragging is used in other areas.

Add a draggable option

---

src/components/m-table-edit-field.js
src/components/m-table-edit-row.js

Since onRowDataChange is not being removed as a prop being passed into child components, and it isn't used by them, this is eventually being put onto a simple div element which causes an error because it isn't recognized. By removing this property from the props that are passed down, this error goes away because ultimately the prop function 'onRowDataChange' isn't being loaded onto the subsequent div element at the bottom of the component chain. When a row is updated, the hook 'onRowDataChange' is still working as expected.
#615 
To stop the prop function 'onRowDataChange' from being passed down the component chain and outside of this library where it eventually gets placed onto a <div> element and causes an error because it isn't recognized.
None
List general components of the …

Add to prop filter

---

src/index.js
types/index.d.ts

None
The single components in src/components are exposed using their unstyled variant.
MaterialTable is exported only with the applied HOC `withStyles` such refusing to extend 
the component. This PR exports the unstyled `MateralTable` as `MTable`.
None
* New feature
Great library - Thanks

feat: export unstyled MaterialTable as MTable

---

.gitignore
src/components/m-table-action.js
src/components/m-table-body-row.js
src/components/m-table-body.js
src/components/m-table-cell.js
src/components/m-table-edit-field.js
src/components/m-table-edit-row.js
src/components/m-table-filter-row.js
src/components/m-table-group-row.js
src/components/m-table-groupbar.js
src/components/m-table-header.js
src/components/m-table-pagination.js
src/components/m-table-stepped-pagination.js
src/components/m-table-toolbar.js
src/default-props.js
src/index.js
src/material-table.js

The [material ui docs state](https://material-ui.com/guides/minimizing-bundle-size/) that in order to minimize bundle sizes you can use full path instead of named imports. For production builds named imports will most likely not be a big issue as webpack's tree shaking solves this. For development builds tree shaking is not enabled and causes the whole `@material-ui/core` module to be imported which could cause slower build speeds and larger bundle sizes. 
This pull request fixes that by replacing the following
```js
import { Button, TextField } from '@material-ui/core';
```
with
```js
import Button from '@material-ui/core/Button';
import TextField from '@material-ui/core/TextField';
```
I was not happy with the build times I was getting on my development builds and tried to optimize all …

Enhancement: Use path imports for @material-ui/core

---

src/components/m-table-action.js

Fix custom actions being smaller than the default ones and being unable to resize
Fixes #839 
Custom actions' size is smaller than the default actions and being applied after the `iconProps` property, which makes it to override the size (if any) applied by the developer.
* src/components/m-table-action.js

Fix custom actions' size

---

src/material-table.js

#703 
Removing 'isInit' from changePageSize to upload the pageSize when using remote data
* material-table.js
Hi!
I need to update pageSize dynamically with ContextAPI, and the "isInit" don't let me do it.

Fixes issue #703

---

README.md
package.json

Material UI complains when multiple library instances are initialized in a single application.
The issue can be easily solved by making `@material-ui/core` a peer dependency plus development dependency, instead of having it as a production dependency only.

Make @material-ui/core a peer dependency

---

demo/demo.js
src/material-table.js
src/prop-types.js

An optional callback property for the MaterialTable component to inform about shown / hidden columns. This makes it easy to persist the current user settings.
branch | PR
column-hidden-callback | [Link](https://github.com/dnn5b/material-table/tree/feature/column-hidden-callback)
This feature has been often requested (e.g. in [here](https://github.com/mbrn/material-table/issues/668)).

Feature: show / hide column callback (#668)

---

types/index.d.ts

Callback is the row clicked, not the whole set

Fix row `onClick` typedef

---

package.json

https://github.com/mbrn/material-table/issues/907
https://github.com/mui-org/material-ui-pickers/issues/1219
Material table depends on material-ui pickers, which had a babel compilation issue. Material UI pickers fixed there issue, and material-table should update its dependency.
https://github.com/mui-org/material-ui-pickers/pull/1223
* Testing
* Babel transpilation
* Webpack builds

Fix for failing jests due to outdated material-pickers babel config error

---

src/components/m-table-header.js
src/material-table.js

Relate the Github issue with this PR using `#936`
In #936 I wanted to be able to sort with 3 states. In this PR it's now possible.
It's now possible to have three states to sort one column.

Add third state to sort column

---

src/components/m-table-group-row.js

-
When you try to group then sometimes you get the warning "Warning: Each child in a list should have a unique "key" prop." because the `freeCells` array renders elements without key. Fixed in this file change
-
* grouping
-

`freeCells` key added

---

src/components/m-table-body.js
src/components/m-table-group-row.js

fixed #945: When rows are grouped by a column, editing does not work
#945
#778
#327
Found this issue a few days before and already fixed it.
Creation of EditRow was not implemented in GroupRow.
m-table-group-row

fixed issue #945

---

types/index.d.ts

Related Issue  [`#1002`](https://github.com/mbrn/material-table/issues/1002)
The goal is to add the missing types for the aria-labels of the pagination object within the localization interface.
None
* The Type definitions index.d.ts

Add aria-label type definition to localization interface

---

src/components/m-table-body-row.js

I cannot find issues related with this. If you find anything related, feel free to add it please.
Fix the bug in `onRowClick` handler (i.e., how `togglePanel` is implemented)
The type of `detailPanel` is described as ` ((rowData: RowData) => React.ReactNode) | (DetailPanel<RowData> | ((rowData: RowData) => DetailPanel<RowData>))[]`. Current version of `togglePanel` of `onRowClick` handler correctly handles the former 2 cases (i.e., `(rowData: RowData) => React.ReactNode)` and `DetailPanel<RowData>[]`) but it has bug on the later case (i.e., `((rowData: RowData) => DetailPanel<RowData>)[]`). This PR tries to fix the bug.
**Same as related issues**
* `m-table-body-row.js`: After this PR, `togglePanel` of `onRowClick` …

Fix `togglePanel` of `onRowClick` event handler

---

package.json

https://github.com/yarnpkg/berry/issues/3
In the upcoming yarn v2 packages should either explicitly provide missing peer deps or forward them
N/A
Installing the package
Fixes the following warnings currently created when install this package with yarn v2:
```
➤ YN0002: │ material-table@npm:1.50.0 [V] doesn't provide @date-io/core@^1.3.6 requested by @material-ui/pickers@npm:3.2.4
➤ YN0002: │ material-table@npm:1.50.0 [V] doesn't provide react@^16.8.4 requested by @material-ui/pickers@npm:3.2.4
➤ YN0002: │ material-table@npm:1.50.0 [V] doesn't provide react-dom@^16.8.4 requested by @material-ui/pickers@npm:3.2.4
➤ YN0002: │ material-table@npm:1.50.0 [V] doesn't provide react@^16.8.5 requested by react-beautiful-dnd@npm:11.0.3
➤ YN0002: │ material-table@npm:1.50.0 [V] doesn't provide …
```

fix: Missing peer dep warning in yarn v2

---

src/prop-types.js
types/index.d.ts

This makes `onChangeQuery` func. available on `MaterialTableProps<RowData>` type 
Currently:
```
Property 'onQueryChange' does not exist on type 'MaterialTableProps<RowData>'
```
is being thrown.

onQueryChange added to types

---

src/components/m-table-header.js
src/default-props.js
src/material-table.js
src/prop-types.js

#985 
It's now possible to sort the table columns with 3 or 2 states. By default `thirdSortClick = true` which makes it possible to sort the table to the state it was in when it was first rendered. 
With `thirdSortClick = false`, it's only possible to sort 'ASC' or 'DESC'.
m-table-header
I set `thirdSortClick` to `true`, because this is the natively behavior of a table. It should allow the user to sort ascending, descending and be able to return to the initial state. If this is not the desired behavior, through the options it is possible to revert:
```jsx
<MaterialTable
data={data}
options={{
thirdSortClick : false
}}
/>
```
Change `sortBackToNormal` to `thirdSortClick` prop name.
Waiting for merge @mbrn

Possibility to sort column with 2 or 3 states

---

types/index.d.ts

https://github.com/mbrn/material-table/issues/948#issuecomment-519097335
According to the [example for tree data](https://material-table.com/#/docs/features/tree-data). parentChildData should take a function that returns RowData not RowData[]

Fix type definition for "parentChildData"

---

src/material-table.js
src/prop-types.js
types/index.d.ts

None
We would like to manage remote data fetching outside the offered Promise based approach by making use of flux/redux like patterns.
For this we need to manage the pagination counters on our own independently of the given `data.length`. Usually {skip, limit, count} response parameters would give the page number and the totalCount.
This PR offers two new properties on `MaterialTable`:
- `prop.page` the number of the page the data-set is related
- `prop.totalCount` the total count of possible data sets
Only if both props are defined, the current behaviour of `MaterialTable` is changed such that the pagination values are managed outside the component. 
The change proposed is fully backwards compatible.
None
* …

feat: foreign handling of pagination counters

---

types/index.d.ts

Fix bug where only object keys can be used as "field" value.
Now should be possible to use field "a.b.c.d" for find key "a" in row and key "b" inside "a", ...
#1130

Deep selector in column field #1130

---

src/components/m-table-body-row.js
src/components/m-table-edit-row.js

#1075 & #1020
Prevents internal props from ending up in the dom
* Table Rows
There are probably better ways of handling this overall, but that would require a more substantial rewrite of the components.

Strips internal props to prevent ending up in the dom

---

demo/demo.js
src/components/m-table-toolbar.js

No related issue at this time.
If passed a react component, render it without being nested inside a <Typography> element.
None
Table Toolbar (`m-table-toolbar.js`)
On a project I'm working on using this component, we were passing in:
```
title={
<>
<Typography variant='h6' color='primary'>{title}</Typography>
<Divider />
</>
}
```
Which resulted in the following error:
`Warning: validateDOMNesting(...): <h6> cannot appear as a child of <h6>.`
This fixes that error :)

Allow Typography to be passed into `title` without throwing an error.

---

src/utils/data-manager.js

#1014 
This PR removes the mutation of the provided data by copying the provided data and not writing to the provided props directly. 
This is in line with the best practices since props should never be mutated and this causes unforeseen side effect. If the data comes from redux or another state management library, these changes persist over the lifetime of the session and might even be played back into the backend if the data is updated and the tabledata is passed as well, since the global object is changed.
This also makes it difficult to reset the selection if the same data is used for multiple tables in which case selection in one table effects the selection of the other, even so they should be separated.
Additionally, the mutation is not mentioned in the documentation which makes …

Remove data mutation

---

src/components/m-table-cell.js
src/components/m-table-edit-field.js

[#534](https://github.com/mbrn/material-table/issues/534) - Editable Currency type render "ok"
When editing a currency field, instead of returning "ok", show a right-aligned textField.  Also, right align currency field render when not in Edit mode.
* Affects MTableEditField and MTableCell
I attempted a previous PR for the same issue earlier - this is a new and improved version.  Still though, I'm new to working with GitHub so would appreciate any feedback.

Fix Currency field Issues - Edit and alignment

---

src/components/m-table-toolbar.js

Didn't find any issue with this.
Prevents `onChangeColumnHidden` callback from being triggered twice as a result of having a label with checkbox inside a container with a click listener.
* Toolbar
* Actions (Column toggler)
When having a click listener on a container and label + checkbox as children the event listener will be called twice when clicking the label. Once for the direct listener itself, and another time for the label causing the checkbox to change, triggering an `onClick` and the event bubbling up to the parent.
Ideally, the checkbox should have the listener (as an interactive element) and label can be used as a button with larger click area. This PR updates the structure and fixes this issue.
See reduced and reproduced issue with an explanation here: …

Fixe bug where onChangeColumnHidden is called twice when clicking label

---

src/components/m-table-body-row.js

#998 
A custom icon passed through the `detailPanel` prop should accept the prop `iconProps` which are then passed to the custom icon. Previously `iconProps` was not being passed to the custom icon.
None(?)
branch | PR
* detailPanel icons
Kind of new to making PRs for OSS, let me know if I'm missing anything.

added iconProps prop to CustomIcon, removed style (undocumented)

---

demo/demo.js
src/components/m-table-action.js

#910 [keeps the previous fix for this in tact]
#1049 [resolves this issue]
Fix issue #1049 and keeps the fix for issue #910 in tact
branch | PR
master | [Fixes issue #910 ](https://github.com/mbrn/material-table/pull/956)
* ~/src/components/m-table-action.js
* ~/demo/demo.js
In issue #910 the tooltip for free actions was displaying very close to the icon button, [the fix for this was removing the span that surrounded the icon button](https://github.com/mbrn/material-table/pull/956).  
This caused a warning on disabled actions per issue #1049.  Adding a ternary to check whether the action is enabled or disabled, so we can add/remove the span, resolves issue #1049 while keeping the fix for issue #910 in tact.
I have created 2 demos …

Fix issue #1049 and keeps the fix for issue #910 in tact

---

src/material-table.js

#1182
This adds the missing addTooltip localization if a custom, partial localization object is passed in combination with edit.
* Material-Table

Fix for #1182

---

src/prop-types.js

This allows functions to be passed as editable parameter.
#1183 
* prop types

Fix for #1183

---

src/components/m-table-cell.js

https://github.com/mbrn/material-table/issues/1158
Table Cell will have default style: `color: inherit` so color styles set on row are inherited by default from but has an override available.
None
* Table Cell Styles

Table Cell sytyle inherits color by  default

---

src/components/m-table-body.js
src/components/m-table-edit-field.js
src/components/m-table-edit-row.js
src/components/m-table-filter-row.js
types/index.d.ts

#1129 
This adds a localisation prop to pass a date-fns locale object within the body to enable datepicker localisation.
Like this: 
` import frLocale from 'date-fns/locale/fr';`
...
`localisation={{body: {locale: frLocale }}}`
This will result in a french datepicker.
* Body
* Edit Field
* Edit Row
* Filter Row
* index.d.ts

Add locale to datepicker

---

src/components/m-table-action.js
src/components/m-table-body-row.js
src/components/m-table-body.js
src/components/m-table-filter-row.js
src/components/m-table-toolbar.js
src/material-table.js
src/prop-types.js
types/index.d.ts

#676 
Implements idea 2 of https://github.com/mbrn/material-table/issues/676#issuecomment-502665435
> I really appreciate your work on Material Table. I've started using it heavily and looking forward to contributing.
> 
> Could lend a hand on implementing this, I think.
> 
> As I understand it there's three types of actions currently:
> 
> 1. `isFreeAction` top bar action
> 2. Top bar action _when rows are selected_
> 3. Actions on rows
> 
> The type of 2 and 3 are currently implicitly defined based on if it's a selectable table. (Please correct me if I'm wrong or missed something)
> 
> I would propose one or these two approaches (backwards-compatible with just deprecating the old API):
> 
> 1. Move row actions to `columns[]`. Would make it very explicit what is where.
> 2. Explicit …

Add position field to action

---

src/material-table.js

Fix async search where the debouncing rolls back the search input while typing
ℹ️ Notice `f` disappearing whilst typing)
https://www.dropbox.com/s/9gpjagettvujeg0/1-before.mov?dl=0 
https://www.dropbox.com/s/d6bfoimuaf45dv9/2-after.mov?dl=0
Can't say I fully grasp the double state management of `dataManger` vs `setState`, but hammered it enough to  get what  I needed working

Fix remote data search flicker

---

src/components/m-table-edit-row.js

#1136
The change makes MTableEditRow's cells use the cellStyle defined.
* MTableEditRow

Make MTableEditRow's cells use cellStyle (related to #1136)

---

types/index.d.ts

N/A
Add type for new option property `thirdSortClick`. Resolves compile issue when using this property in TypeScript. 
N/A

Add type for new option prop thirdSortClick

---

src/material-table.js

This will remove the deprecated componentWillReceiveProps and moves the code snippet in didUpdate. The reduce will check, if the props changed and will only trigger the setDataManagerFields update, if the props did change. This will help make the migration towards Concurrent move, since the willReceiveProps lifecycle method will not work with cocurrent mode.
* Material-table

Remove UNSAFE_componentWillReceiveProps

---

src/components/m-table-body-row.js

#1213 
`options.cellStyle` props is not actually being passed down to `cell` `columnDef` props but already being used. As a result, styles don't reflect.
Custom styling of Cells as mentioned in #552 doesn't work.
If you have any suggestions or concerns i am more than happy to hear it. Thanks a lot for this tool, i am one of those who's actually using it! :D

Bugfix: Passing cellStyle to ColumnDef props

---

src/material-table.js
src/prop-types.js
types/index.d.ts

#367 
Expose onFilterChange as an event that fires when a table's filters are changed
None that I could find
onFilterChangeDebounce in material-table.js, and associated types
Our team needs to get searched and filtered data back out of material table in order to show summary information. OnSearchChange works well as a place to hook into tableRef's data, but there was no accompanying event for filters. We have no immediate need for the filters applied to the table, so let me know if there's a more appropriate event param.

call onFilterChange

---

src/material-table.js

#1223 
Config for validating when applying `defaultSort` is not checking the options for `sorting: false`. Also when applying it directly at the `column`. As per the documentation, this should not be the case.
Sorting of columns.
Just let me know if you have any concerns so I can immediately coordinate.

bugfix: disable defaultSorting when sorting = false

---

src/components/m-table-action.js

#1235
Prevent action icons to re-render unconditionally.
* MTableAction

#1235: prevent actions icons re-render

---

src/components/m-table-filter-row.js

Local bug
Wrong top margin in FilterRow property lookup
Custom style. component Select, style marginTop in MTableFilterRow

Bugfix: marginTop in TableFilterRow

---

src/components/m-table-groupbar.js

The Group by Chip Label is coming out to misaligned. vertically.
branch | PR
*

Fixed label of groupby chip misalignment issue

---

types/index.d.ts

#1298 #1225 #1265
missing property searchText for typescript

Missing property searchText in TS def

---

src/material-table.js

I openned an issue today #1336, and this fixes that.
When props change, `componentDidUpdate` calls `setDataManagerFields` with the new props. 
But it calls `setDataManagerFields(props)`, and `setDataManagerFields` receives two parameters (`props` and `isInit`). 
I don't have the time to check if passing `setDataManagerFields(props, true)` breaks anything, so I removed the validation `isInit && this.dataManager.changePaging(props.options.paging);` to just `this.dataManager.changePaging(props.options.paging);`. In that way, the `DataManager` knows that **now** the table has paging, and the `renderData` isn't the whole `data` prop.

Solves the problem when options.paging changes dynamically

---

types/index.d.ts

This will allow the custom elements to accepts props, which they need. Previously, it would throw a type error to call them with props:
`<MTableBodyRow {...props} />` failed.

Allows the custom elements to accept the needed props

---

src/components/m-table-action.js

isEditable conditional is broken in version 1.54.1 #1321
Fixes a bug that is causing the `editable` property's `isEditable` and `isDeletable` options to be ignored.

Fix issue #1321: broken isEditable and isDeletable options

---

src/material-table.js

#1376
This adds the missing onChangePage call on onChangeRowsPerPage and the page is set to 0.
* material-table

Call onChangePage on changePageSize

---

src/utils/data-manager.js

An error occurred if using null value.
```
data-manager.js:180 Uncaught TypeError: Cannot read property 'toString' of null
at data-manager.js:180
at Array.filter (<anonymous>)
at data-manager.js:177
at Array.forEach (<anonymous>)
at DataManager.filterData (data-manager.js:166)
at DataManager.getRenderState (data-manager.js:119)
at MaterialTable.<anonymous> (material-table.js:355)
```
Thanks for your great library :)

Fix the error when lookup value is null.

---

types/index.d.ts

I haven't opened an issue for this, but current types do not work with react apollo hooks generated with graphql-codegen
See 
Because the functions available through the hook have a stronger Promise return Type 
This PR is meant to enhance compatibility of this library with apollo react and graphql-codegen
* none
This will only affect types and **is not** a breaking change since it's more permissive, but imo the original type was restrictive and worked well by directly returning a Promise object, which does not cover use cases with third party librairies 
For now the workaround for using react apollo and graphql-codegen is to edit the types files directly in the node_modules folder

fix(types): change void to any for promises return on editable callbacks

---

types/index.d.ts

Fixes duplicate identifier typescript error:
```
$ tsc
./node_modules/material-table/types/index.d.ts:231:3 - error TS2300: Duplicate identifier 'searchText'.
231   searchText?: string;
~~~~~~~~~~
./node_modules/material-table/types/index.d.ts:234:3 - error TS2300: Duplicate identifier 'searchText'.
234   searchText?: string;
~~~~~~~~~~
Found 2 errors.
```

Remove duplicate Options.searchText typing

---

demo/demo.js
src/components/m-table-toolbar.js
src/default-props.js
src/material-table.js
src/prop-types.js

#1291 (Partially)
Added the ability to chose the variant of the search field by providing **searchFieldVariant** under the **options** props.
The possible values are _standard_, _filled_ , _outlined_.
If not provided the default value is standard
`
<MaterialTable>
...
options={{
searchFieldVariant: 'outlined',
}}
</MaterialTable>
`
* MTableToolbar component
* Demo application which was updated to showcase the change
There was also an attempt to provide the ability to chose variant for the filter fields. The problem was with the lookup filter which did not render the correct variant but kept using the standard one as shown in the picture below. 
This might be related to #1061. Due to this inability to change the variant of the lookup filter, no change was made to the other filters to …

Add the ability to chose the variant of the search text field

---

types/index.d.ts

The usage below works as it is supported in the code but when using TypeScript (I am on 3.7.x) it complains about the field labelled "icon" being incorrect. I have update the types based on [@material-ui/icons](https://github.com/mui-org/material-ui/blob/e168bc694a7c7a59e86990e2a3677938acf7e953/packages/material-ui-icons/scripts/create-typings.js#L24). Since this project does not include "@material-ui/icons", I just recreated the type in the same way they did it on line 24. 
`
import { Save } from "@material-ui/icons"
import { Action } from "material-table"
const saveAction: Action<{ id: number}> = {
icon: Save,
tooltip: "Save",
onClick: () => { /* ... */},
}
`

Update action types to support current icon usage

---

src/material-table.js

#1554 
Simply disable add button when a row is being edited. When a new row has been added the add button is still visible though.

Disable add button when in edit mode

---

src/prop-types.js

#1387 
Fix the warning that arises when passing a ForwardRef as an icon to `detailPanel`. If you install the material icons as listed [here in the readme](Warning: Failed prop type: Invalid prop `detailPanel`), you may run into this warning when passing an icon ForwardRef as a prop, as showed in #1387 .
* `detailPanel` prop in `MaterialTable`
A current workaround to silence the warning:
```
import AccountCircle from '@material-ui/icons/AccountCircle';
...
<MaterialTable
...
detailPanel={[
{
icon: () => <AccountCircle />,  // <------------- here
tooltip: 'Show Account',
render: rowData => <Redirect to={`/profile/${rowData.id}`} />,
},
]}
/>
```
It makes more sense though to allow `RefComponent` prop type since the other …

Fixes the unnecessary PropType warning in #1387

---

src/material-table.js

#491 
but actually many more like #1272 (partially solved) #1265
This PR introduces a fair equality check between columns when using remote data.
Without this pr, while checking in component did update if the columns changed, `this.props.columns` and `prevProps.columns` assumed different forms hence the deep equal returned false for the first time causing a rerendering of the entire table losing every setting set, and true at the second time.
This happens because through the data-manager the tableData property is added only in a second time to this.props.columns.
* the entire material-table.js component is affected

fix: remove tableData property from column in check phase

---

src/material-table.js

Part of editing mode is captured on the tableData field of the individual row's data object.
This field is overwritten when new row data is provided to the table.
Overwriting this field without dropping the lastEditingRow in
DataManager causes the entire table to become locked.
Add call to DataManager#changeRowEditing to drop all references to
editing rows. This prevents table from becoming locked when row data is
updated while editing.
https://github.com/mbrn/material-table/issues/1610
#1610 
#1595
#1527
#1487 
#1446 
Prevent table from having all rows locked in edit mode when a row data change occurs by resetting the editing state captured in MaterialTable and DataManager.
None
* MaterialTable when editable is defined.

Fix rows becoming locked when edit state is lost

---

src/material-table.js
src/utils/data-manager.js

[#1323 ](https://github.com/mbrn/material-table/issues/1323)
Skip the sorting if the data could be already sorted from backend. Checking type of `this.props.data`  and skip the sorting if it is a function.
branch | PR
*  [material-table.js](https://github.com/mbrn/material-table/blob/master/src/material-table.js)
*  [data-manager.js](https://github.com/mbrn/material-table/blob/master/src/utils/data-manager.js)

Checking props.data type to skip remote sorting

---

types/index.d.ts

Allow passing in React components as localization options. This allows for example changing typography, "tagging" strings with data attributes for testing, etc.

Allow `React.ReactNode` for certain localization strings

---

src/components/m-table-body-row.js

#1241
Fixes the issue described in #1241, where detail panels, when used in combination with tree data, would cause the detail panel for the parent row to appear below all child rows of that parent. 
Now the parent detail panel will appear directly below the parent itself, as I believe is most natural, if for some reason you feel this is not the way it should work, I can add it as an option instead.
Also included in this pull request is a change to the ordering of the button icons for detail panels and tree data when used in combination.  
Previously the tree data icon would appear after the detail panel icon when the detail icon was set to appear on the left side.  
This felt very unnatural, especially if the detail icon was hidden on certain rows. 
If for some reason you feel this is …

Fixes for combination of detail panels and tree data

---

src/utils/data-manager.js

#1121 
Fixes a bug that would cause the iconbutton (action/detail/tree etc) on the right side to take on the "extra" space "leftover" when hiding columns. See the related issue for how this looks.   
This is fixed by filtering out hidden columns when checking the length for the CSS `calc`. 
None that I could find.
* data-manager.js

Fix: Action/Detail/Tree spacing with hidden columns

---

src/components/m-table-toolbar.js

Relate the Github issue with this PR using #1293 and #1348
Previous [commit](https://github.com/mbrn/material-table/commit/8cda5e7b208799ecc440fa15de92ef852c11a88d) removed one of these invalid props, but two remained which are not implemented in latest Material UI

Removed color="inherit" from search InputAdornment

---

src/material-table.js
src/prop-types.js
types/index.d.ts

#1719 
Adding isEditHidden and isDeleteHidden optional props to "editable" prop to allow hiding Edit and Delete buttons based on rowData
N/A
Action component
I stumbled with same requirement as in #1719 . I am using material-table to display hierarchical data. However wanted to hide the Edit/Delete buttons in node rows. Without this solution I can only disable the buttons, however it looks better when icons are hidden.

Adding isEditHidden and isDeleteHidden to editable prop

---

src/prop-types.js

I didn't create issue. I thought it will be easier, if I simply provide solution for my problem and maybe problem of other users of Material Table
Material Table documentation (https://material-ui.com/components/tables/#custom-pagination-options) specifies that pagination can use not only options of type number, but also objects with the value and label keys, which will be used respectively for the value and label of the option (useful for language strings such as 'All').
* Pagination

Add named pageSizeOption value

---

src/components/m-table-toolbar.js
src/material-table.js
src/prop-types.js

#1985
This fixes the searchText regression, where the filter is applied, but the initial value is not written to the input field
* prop-types
* table
* toolbar

searchText fix

---

src/components/m-table-header.js

#1369
Sets the default alignment of a currency column to align right rather than left. Currency cells align to the right whereas the headers align to the left which is inconsistent for the column as well as numeric cells.

Update header alignment of currency header.

---

types/index.d.ts

On my **local** project ;)
This PR is meant to allow to use the **onRowDataChange** props in **editComponent** Column object attribute.
My project is in **TS** and the type declaration for this one was **missing**
It will affect **only the TS types** !
*
**Thanks** for the incoming revue ;)

fix(editComponent): add missing onRowDataChange type declaration

---

src/material-table.js

None
This pull request fixes an off-by-one error which causes the incorrect column width to be used for the vertical line delineating the fixed from unfixed columns.
None
* [Fixed Columns](https://material-table.com/#/docs/features/fixed-columns)
None

Fix off-by-one error for fixed table layouts

---

src/components/m-table-edit-row.js

#1908 
The paddingProp is also applied to the EditRow.
-
* m-table-edit-row.js
This makes sure that the table has the same look and feel even when you are editing or deleting rows. See screenshot from the change:

Dense padding prop is applied to EditRow

---

src/components/m-table-body.js
src/components/m-table-filter-row.js
src/prop-types.js
types/index.d.ts

There exists support for filter cell styling via the `filterCellStyle` prop(s).  It would be useful to extend similar functionality to the FilterRow via a similar property in `options`, `filterRowStyle`.
* FilterRow

add support for FilterRow styling to options

---

demo/demo.js
src/components/m-table-edit-field.js
types/index.d.ts

Allow overriding of placeholder for editing fields. This allows easier hinting of what to fill in for users editing/adding to table
Sorry for the extra formatting, my vscode has auto formatting against trailing spaces 
* MTableEditField
Hi Carlson! :)

Allow overriding of placeholder for editing fields

---

src/components/m-table-body-row.js
src/components/m-table-edit-row.js
src/prop-types.js
types/index.d.ts

Related to #1956 
Add new option called `detailPanelColumnStyle`, working like `actionsCellStyle`
m-table-body-row.js
Thank you for this amazing library ❤️

add capacity to style the detail panel column <td> via detailPanelColumnStyle prop

---

src/components/m-table-cell.js
src/components/m-table-header.js
types/index.d.ts

#736 
This enables the override of the cell align to match the available [props from material-ui](https://material-ui.com/api/table-cell/#props).
By adding `align` to the column def, it will be passed down to the header and the cells for that column. It will override the default align which is either left or right for numeric values.
If not provided, the previous used alignment strategy will be the fallback.
The types are updated as well with all possible options:
`'center' |'inherit' | 'justify'|'left' |'right';`
* types
* TableHeader
* TableCell

Add align to tableCells from columnDef

---

src/material-table.js

#1868
This PR fixes #1868 by reordering the columns, if the default column sorting changes and the current sorting differs from that.
This fixes a bug, where the sorting of defaultSort columns is skipped, if the columns are initialized after the table is rendered, for example in a useEffect callback.
For details, see the attached issue.
This also allows the user to trigger a sort by changing the column object programmatically for example on a button click.
* Material Table => setDataManagerFields

Trigger reorder if column default sort changed

---

src/components/m-table-header.js

This adds hideSortLabel to TableSortLabel used in the actions header. From what i can see it's never being used, and it takes up a lot of space.
MTableHeader

Added hideSortIcon true to TableSortLabel for actions

---

src/components/m-table-cell.js

#1830 
When rowStyle option contains `fontSize`, `fontFamily` or `fontWeight`, the table cell does not take those styles.
To achieve that, the cellStyles have those properties with `inherit` value.
* TableCell

Added CSS font properties to inherit in cellStyle

---

src/components/m-table-filter-row.js

Fixes #2021. The event.target from the onClose method of the Material UI Select was undefined. This uses the controlled selectFilter state instead of relying on `event.target.value`.
* Remote data lookup filters

Close #2021

---

types/index.d.ts

N/A
`totalCount` is missing on the query interface, while it's defined on the query object: https://github.com/mbrn/material-table/blob/5a5eca0114f5a81c96c3c848bb6308c241828d91/src/material-table.js#L45 
N/A
typescript typings

fix(typings): added missing totalCount type on Query interface

---

src/components/m-table-filter-row.js

I was able to resolve the bug that does not filter the table results after clicking a lookup filter without creating an issue, but will open one if necessary
After rendering a table that has a column containing a `lookup`, then in the UI after selecting a lookup filter from the Select dropdown the Table does not update with the filtered result set
Bug Demo: https://codesandbox.io/s/material-tablelookup-filter-bug-m9lmi?file=/src/App.js
Inside the `m-table-filter-row.js` component there is an onClose handler that passes `event` into `this.props.onFilterChanged(columnDef.tableData.id, event.target.value);`. When onClose is called `event` is `undefined`, which is the source of the bug. Since `m-table-filter-row.js` already has declared a piece of state that has the `selectedFilter`, I have …

[Bug]: Table results do not filter after selecting a lookup filter

---

package.json

#2066
Updated `react-beautiful-dnd` to version `^13.0.0`. This version has the possibility of adding a `cspNonce` which the current version `11.0.3` does not have.
In this PR #1438 , the possibility of adding a `cspNonce` to `material-table` options was added but it is not woring because of outdated `react-beautiful-dnd`.

[BUG]: Content Security Policy nonce option is not working

---

src/components/m-table-edit-field.js

Datepicker localization not working
Parameter name is passing as locale from m-table-edit-row to m-table-edit-cell.
But it wrongly written as dateTimePickerLocalization.
PR fixes datepicker localization problem.
branch | PR
*

datepicker localization fix

---

src/material-table.js

#1785 
#322
when both `selection` and `parentChildData` are used together, `onSelectionChange` callback receives duplicate rows, because there's a logic inspecting `tableData.childRows` while iterating rows, but since the function is already iterating every rows including child rows, there's no need to check child rows twice in this case.
I've only tested with 1 level depth tree data, so not sure if there are other corner case

Fix redundant recursive check in onSelectionChange

---

src/components/m-table-edit-field.js

Passing `valueAsNumber` instead of `value` when the field is numeric

Fix onChange when numeric value

---

types/index.d.ts

Fix name error on RowData in index.d.ts
ERROR in [at-loader] ./node_modules/material-table/types/index.d.ts:294:25 
TS2304: Cannot find name 'RowData'.
This was due to the fact that the RowData type variable available in MaterialTableProps should be transmitted to the Options type.

Fix typescript error TS2304: Cannot find name 'RowData'

---

src/material-table.js

Currently it's send query state pageSize on without remote data pagination onChangePage.

Send correct pageSize onChangePage without remoteData

---

src/material-table.js

When I use the options:
``` javascript
options: {
fixedColumns: {
right: 1,
},
}
```
I found that the width of the right fixed column will use the width of the first column. So I found the code below:
``` javascript
for (let i = 0; i < Math.abs(count) && i < props.columns.length; i++) {
const colDef = props.columns[i >= 0 ? i : props.columns.length - 1 - i];
if (colDef.tableData) {
if (typeof colDef.tableData.width === "number") {
result.push(colDef.tableData.width + "px");
} else {
result.push(colDef.tableData.width);
}
}
}
```
The Code `i >= 0 ? i : props.columns.length - 1 - i` do not trigger the latter, and the right fixed column use this func like: `width: this.getColumnsWidth(props, -1 * props.options.fixedColumns.right),` with a negative width.
When I changed this line of code, …

Fix invalid expressions

---

types/index.d.ts

Fixes #2171
Fixes #2119
Should be React.ReactNode and not React.Node
https://github.com/mbrn/material-table/pull/2119
\* import error
n/a

fix React.node issue

---

src/components/m-table-toolbar.js

#1359 
I changed the filtering criteria to match the logic described in the comments of issue 1359.
It previously excluded all columns flagged as hidden, no matter the export flag. It now includes those that are marked hidden if also marked for export.
Exporting a table
This is my first time contributing to any open source. The first commit was unnecessary, the second one has the code that has been tested and actually fixes the solution. Open to feedback, hoping to contribute more as I finish school!

Allow export of hidden columns

---

types/index.d.ts

Let the typescript programmer use the field 'initialFormData'

Typescript: Added field 'initialFormData' to MaterialTableProps

---

src/components/m-table-edit-field.js
src/material-table.js
types/index.d.ts

This PR centers the checkbox for the edit boolean field correctly by removing the right padding.

Correctly centers the boolean checkbox

---

demo/demo.js
src/default-props.js
src/material-table.js
src/prop-types.js
types/index.d.ts

#540 
This allows a user to specify the position of the footer containing the pagination with a new paginationPosition prop. Acceptable values are top|bottom|both, with "bottom" being set as the default.
None
Table Pagination
\*

Added prop to support pagination on top, bottom, or both

---

src/components/m-table-edit-row.js

#1364
#1162
Fixed a bug from PR #2008 
* Approve save onEnter will be skipped for text-area a.k.a Material UI TextField mutliline
* Added shift + enter for approve save added for text-area
#2008 
* Edit Row
* Add Row

Fixed  Approve onEnter overriding textarea behavior

---

src/material-table.js

Relate the Github issue with this PR using `#1998`
stepped through THE CATCH AND it does look to set state for errorState as expected, but nothing is rendered
I think maybe the logic is off you set errorState like below
```
["catch"](function (error) {
var localization = (0, _objectSpread2["default"])({}, MaterialTable.defaultProps.localization, _this.props.localization);
var errorState = {
message: (0, _typeof2["default"])(error) === "object" ? error.message : error !== undefined ? error : localization.error,
errorCause: "query"
};
_this.setState((0, _objectSpread2["default"])({
isLoading: false,
errorState: errorState
}, _this.dataManager.getRenderState()));
});
```
but you are checking this for the display.
```
this.state.errorState && this.state.errorCause === "query"
```
I think it …

Fix Bug with displaying error text

---

src/components/m-table-body-row.js
src/components/m-table-cell.js

Fixes #2244
React is warning that `cellEditable`, `onCellEditStarted`, and `onCellEditFinished` are not recognized props for DOM elements. This PR fixes the places those were accidentally passed through.
| feature-1471-editable-cell | [#2242](https://github.com/mbrn/material-table/pull/2242) |
* Editable cells
This should not change any functionality - only remove warnings that the named props are not recognized on DOM elements.

Fix React warnings for cellEditable, onCellEditStarted, and onCellEditFinished

---

types/index.d.ts

Column type is missing hiddenByColumnsButton property.
Without that field you cannot set column to be hidden by default and also available to be shown with "Add or remove columns" window.
- "Add or remove columns" window

Missing hiddenByColumnsButton in Column type 

---

src/components/m-table-body-row.js

While generating results for `renderColumns` using `.map`, `this.props.components.EditCell` component doesn't have a key prop specified, which results in the following warning:
\*

Add key prop for EditCell component in MTableBodyRow

---

src/components/m-table-body.js
src/components/m-table-edit-field.js
types/index.d.ts

This fixes a few missing dateTimePickerLocalization passes and allows to set the format of the datepicker by adding a format to the column dateSetting definition.

Fix for formating the edit datepickers

---

src/components/m-table-body.js
src/components/m-table-filter-row.js

#1538 
Filter row gets misaligned when the details panel column is aligned right.
N/A
* m-table-filter-row.js
* m-table-body.js

Filter row misaligns when details panel column is to the right.

---

src/components/m-table-edit-row.js

#1163
#1355
Currently falsy values except `0` are ignored as `initialEditValue`. This PR allows falsy values including `false` and `undefined`.
#1177
* table-edit-row

Allow falsy value as initialEditValue

---

package.json
src/components/m-table-toolbar.js

#2109 #2137 
Upgraded jsPDF to next version.
This removes the FileSaver GitHub dependency that was preventing people from upgrading to next version of material-table.
https://github.com/MrRio/jsPDF/issues/2208
m-table-toolbar
The require statement within m-table-toolbar.js has been edited as jsPDF is no-longer a default export in v2.0.0 (see https://github.com/MrRio/jsPDF/releases/tag/v2.0.0).
AutoTable also needed to be upgraded to support jsPDF 2.0.0 (see https://github.com/simonbengtsson/jsPDF-AutoTable/releases/tag/v3.5.9).

Upgrade jspdf and jspdf-autoTable dependencies

---

demo/demo.js
src/components/m-table-edit-field.js
src/components/m-table-edit-row.js

Fixes #2284, fixes #2304, fixes #2276, fixes #2269
This removes the unnecessary spreading of onBulkEditRowChanged from the editRow and editCell.
Also it fixes the breaking error if onBulkEditRowChanged is not passed during add/edit.
It also improves the demo add/edit code.
* Demo
* EditField
* EditRow
@mbrn I think is will be really important to be fixes fast, because the add/edit functionally does not work currently.

Removal of onBulkEditRowChanged from spreaded props

---

src/components/m-table-toolbar.js
src/material-table.js

Fixes #2177 Fixes #2187
This prevents the reset of the order for remote data to prevent out-of-sync sorting directions between the query and the current sorting of data-manager.
#2330
* Material-Table

Change the reset of the order direction for remote data

---

src/components/m-table-body-row.js
src/components/m-table-cell.js
src/components/m-table-edit-field.js
src/components/m-table-edit-row.js

Fixes #2357 Fixes #2370
Removes `scrollWidth` from spread props to avoid warnings.
| feature-column-resizing | #2351 |
* Lib setup

Fix props warnings

---

package.json

Fixes #2326
Update jspdf version to 2.1.0 fixing the warnings there.
| ollyrowe:upgrade-jspdf | #2311 |
* The library setup

Upgrade jspdf to v2.1.0

---

src/components/m-table-edit-field.js

In `MTableEditField`, some `material-ui` input components were being passed
`inputProps`, which are for passing attributes to the rendered `input` element,
inside `InputProps`, which are for passing props to the wrapped `material-ui`
`Input` component. This resulted in the `aria-label` for these components
(which was all that was being passed in `inputProps`) being incorrectly applied,
throwing a development error and failing to render the `aria-label` in the DOM.
- `MTableEditField`

Fix `inputProps` incorrectly nested under `InputProps`

---

src/components/m-table-edit-field.js
src/utils/common-values.js

This PR fixes an infinity loop generated by the while loop, where the index is increased each turn and will always be above -1. This happens if the table is mounted repeatably in fast succession.
[Link to SO](https://stackoverflow.com/questions/63602354/material-ui-react-table-hangs-on-switching-tabs)
* common values

Fixes infinity loop

---

package.json

#2720 #2730
Add major version pin for `@date-io/core` and `@material-ui/core` plus `^16.8.4 || ^17.0.0` for `react` and `react-dom`.

Fix NPM7 Peer Dependencies
