CONTRIBUTING.md, README.md, docz/contributing.mdx, docz/get-started.mdx, docz/props.mdx, package.json
This should close #57. 
Feel free to review the PR and if there's something wrong let me know so I can fix it asap :)
=> Add contributing docs to project and docz

docz/examples/example-dates.mdx, package.json, src/m-table-filter-row.js, src/material-table.js
Added date and time pickers for date columns using `material-ui-pickers` with some examples on docz, according to #35.
Any doubts feel free to leave a comment :)
=> Add date time pickers filter feature with documentation

src/material-table.js
=> if value is not undefined

docz/examples/example-actions.mdx, docz/props.mdx, index.d.ts, src/m-table-body-row.js, src/m-table-header.js, src/material-table.js
#69 
Actions would be rendered at column index requested by developer
branch | PR
*
=> Actions would be rendered at column index requested by developer

README.md
Since we created a chat on Gitter, this PR contain changes adding the link and some small fixes on Readme.
Feel free to update or make changes :)
=> Add Gitter and improve Readme

docz/examples/example-actions.mdx, docz/examples/example-basic.mdx, docz/examples/example-cell-styling.mdx, docz/examples/example-dates.mdx, docz/examples/example-localization.mdx, docz/examples/example-options.mdx, docz/examples/example-selection.mdx, docz/examples/example-sorting.mdx, docz/props.mdx, index.d.ts, src/m-table-header.js, src/material-table.js
#80 
Columns and table sorting feature can be activated or disabled and data can have default sorting feature. 
branch | PR
*
=> Adding sorting feature to column and table

docz/props.mdx, index.d.ts, src/material-table.js
challenge accepted! #98  
Added a searchable property  which allows for overriding the default behavior of excluding hidden fields from search
Column definition and apply search function
=> Added a "searchable" property ❤️

docz/examples/example-selection.mdx, src/material-table.js
#96 
be able to load data with already checked rows
* example-selection.mdx
* material-table.js
=> feat(check): possibility to load already checked rows

docz/examples/example-selection.mdx, src/material-table.js
Reverts mbrn/material-table#101
=> Revert "feat(check): possibility to load already checked rows"

src/material-table.js
#97
Exposes paging and sorting handlers
=> Exposes paging and sorting handlers

docz/examples/example-actions.mdx, src/filterActions.js, src/m-table-body-row.js, src/m-table-body.js, src/m-table-filter-row.js, src/m-table-header.js, src/m-table-toolbar.js, src/material-table.js
None currently, can raise one if required
Adds more options to rendering row and selected actions.  Have added examples documentation.  Does not break/change existing behaviour.
There is a touch of duplicated code, can refactor to use a helper if preferred
=> Adds more options for rendering actions

index.d.ts, package.json
Fixes errors in `index.d.ts` and adds a lint check to prevent this from happening again.
=> Fix Typescript definitions

docz/examples/02-example-column-types.mdx, docz/props.mdx, index.d.ts, src/m-table-cell.js, src/material-table.js
=> This closes #123

docz/examples/12-example-others.mdx
Apparently, the way the localization works changed and was not reflected within the docs.
Fixes a change in the way, the localization object works.
The Docs
=> Fix error in localization

index.d.ts
The Icons have to be a function to return the Icon element, not the JSX.Element directly.
branch | PR
*
=> Fix types for Icons override

src/m-table-filter-row.js
#165 
Add key to TableCell component in m-table-filter-row.js for the action column
=> fix(table filter): add key to TableCell for action column

index.d.ts
=> Add onRowClick to the index.d.ts file

index.d.ts
=> Update types for localisation

package.json, src/demo.js, src/m-table-body-row.js, src/m-table-body.js, src/m-table-group-row.js, src/m-table-header.js, src/material-table.js
=> Feature grouping

src/m-table-body.js, src/m-table-group-row.js
Now, the rows of grouped rows can be clicked
* material-table
* material-grouped-row
=> Hand on Click down to Row through grouped rows to enable onClick

index.d.ts
Also fixes some smaller stuff with the icons and formating.
=> Update to include export of components

docz/props.mdx, src/m-table-toolbar.js, src/material-table.js
It would be nice to disable the title in the toolbar and align the searchbar and buttons on the left.
* material-table
* m-table-toolbar
=> Toolbar title and button alignment

index.d.ts, src/demo.js, src/m-table-body-row.js, src/m-table-body.js, src/m-table-cell.js, src/m-table-filter-row.js, src/m-table-group-row.js, src/m-table-header.js, src/m-table-toolbar.js, src/material-table.js, src/utils/data-manager.js
=> Data manager

src/utils/data-manager.js
bug fix TypeError: Cannot read property isExpanded of undefined
=> bug fix TypeError: Cannot read property isExpanded of undefined

docz/props.mdx, index.d.ts, src/m-table-body.js, src/m-table-edit-row.js, src/material-table.js
I added the localization of the edit row component and for the edit actions.
=> Editrow localization

docz/props.mdx, index.d.ts, src/m-table-pagination.js, src/m-table-stepped-pagination.js, src/material-table.js
#305 
This shows the pagination with numbers and makes navigation overall easier.
- Material-Pagiantion
- index.d.ts
- docs
=> Stepped pagination

index.d.ts
=> Add accidentally removed strings

docz/props.mdx, index.d.ts, src/material-table.js
#371 
Add localization for label on select
pagination
=> Add localization for label on select

src/m-table-pagination.js
=> Fix localization for pagination component

src/material-table.js, src/utils/data-manager.js
=> Add option to expand all rows by default

src/m-table-body-row.js, src/m-table-body.js, src/m-table-edit-row.js
=> Fix bug when try edit child rows

src/m-table-toolbar.js
=> Fix display 2 search box when select an item

src/form/form-field.js, src/m-table-body.js, src/m-table-edit-row.js, src/material-table.js
=> Add support for Formik

src/demo.js, src/utils/data-manager.js
=> Fix option default expanded not working

src/m-table-edit-field.js
Warning: Failed prop type: Invalid prop `value` of type `boolean` supplied to `Checkbox`, expected `string`.
branch | PR
*
=> Fix bug Invalid prop `value` of  `Checkbox`

index.d.ts, src/material-table.js
Allow to customize header title
Header
=> Allow to customize header title

docz/props.mdx, index.d.ts, src/demo.js, src/m-table-edit-row.js, src/material-table.js
=> Add flag editable of column

index.d.ts
#482
Simple interface fix to help development with typescript
=> Added filters to the query interface

index.d.ts, src/m-table-cell.js
add `rowData` as second parameter to `cellStyle` if it's a function.
=> This closes #519, cellStyle takes rowData

package.json
#553 
Bring react version up-to-date with react-dom version
Although the area of impact is system-wide, there are no backwards incompatible changes with this release.
=> bring react version up to date with react-dom version

src/components/m-table-body-row.js, src/components/m-table-header.js, src/default-props.js, src/material-table.js, types/index.d.ts
#549
Able to align the detail panel columns to the right hand side of the table
* Table header
* Table body
* Detail panel columns
=> Feat: able to align the detail panel icon column to right

types/index.d.ts
=> Add rowData to Props

src/components/m-table-toolbar.js, src/default-props.js, src/material-table.js, src/prop-types.js, types/index.d.ts
New Feature: Adding the possibility throw a boolean value that, show or not the the text appear after a checkbox is selected. 
2- Fixing typescript in onSelectionChange function, so it show now that return 2 values.
branch | PR
*
=> Adding posibility to show or the text that appear when the checkbox is selected 

src/components/m-table-edit-row.js
#714 
Implemented fix as described in the issue
=> Fixes issue #714

README.md, types/index.d.ts
This PR updatest the docs and types to work with material-ui v4 and forwardRef to display the tooltip for custom icons.
Readme.md
types.d.ts
=> Pass tooltip to custom icons

demo/demo.js, src/components/m-table-filter-row.js
Now the user can pass a prop in element of the column named 'filterPlaceholder' and the value that he wants
Ex: 
_column: {[
{ title: 'Id', field: 'id', **filterPlaceholder: 'placeholder'** },
]}_
Afects the component **m-table-filter-row** only on function **renderDefaultFilter**
=> Add the possibility add placeholder on filtering

src/utils/data-manager.js
#750 
resets page to 0 when changing search text
=> reset page to 0 when searching

src/material-table.js, types/index.d.ts
None
Expose the onSearchChange handler via property.
None
* None
Please see https://github.com/spurreiter/material-table-remote for a working sample
=> feat: expose onSearchChange

src/components/m-table-stepped-pagination.js
Only adding a key props to page buttons
Fixes #746 
* MTablePagination
=> FIX : Warnings when options.paginationType == 'stepped'

src/components/m-table-group-row.js
=> Render HTML/React column headers when grouped

src/components/m-table-body-row.js
#618 
Fix detail panel column width
=> Fixes issue #618

src/components/m-table-edit-row.js
default values for new row Data
branch | PR
*
=> default values for addRow

src/utils/data-manager.js
#655
#545 
#498 
fix tree data selected row count
=> fix tree data selected rows #655

src/components/m-table-edit-row.js
=> Fixes issue #900

src/components/m-table-body-row.js, src/prop-types.js, types/index.d.ts
Add level param for more row styling possibilities
* m-table-body-row.js
* prop-types.js
* index.d.ts
=> feat: add level param to functional rowStyle

src/components/m-table-header.js, src/material-table.js
#908 
Override sortarrow icon bug fixed
=> Fixes issue #908

src/components/m-table-toolbar.js
=> Fix when drag column export csv column order bug #384

src/material-table.js
[#792](https://github.com/mbrn/material-table/issues/792)
Implemented fix as described in the issue
=> Fixes issue #792

types/index.d.ts
#924 
Add missing type for draggable prop.
=> Add draggable type

src/components/m-table-action.js, src/components/m-table-toolbar.js
#910 
fix tooltip position (remove span tag)
=> Fixes issue  #910

src/index.js, src/utils/polyfill/array.find.js, src/utils/polyfill/index.js
#847 
Fix ie11 array find error
=> Fixes issue #847 (ie11)

demo/demo.js
```javascript
filtering: 'true' to
filtering: true
```
=> Update demo.js (filtering is boolean)

src/components/m-table-body-row.js
#1154 
This adds the missing getFieldValue to EditRow so that #1154 is fixed
* Body Row
=> Adds missing getFieldValue

src/components/m-table-edit-row.js
#1163 
Allow integer 0 as default value
* table-edit-row
=> Allow integer 0 as default value

src/material-table.js, src/utils/data-manager.js
fixed issue #968: Header checkbox is not working properly when groupi…
#968
=> fixed issue #968

src/components/m-table-filter-row.js
#1132 
This adds a small x to enable the clearing of the filter.
* Filter Row
=> Add clear to filter TextField

demo/demo.js, src/material-table.js, src/prop-types.js
Added searchText option to initialize search field before table was render.
=> Added searchText to options.

src/material-table.js, src/prop-types.js, types/index.d.ts
=> #1233 Add minBodyHeight to available options

src/material-table.js
=> Fixed bug connected with searchText and state.

src/default-props.js, src/material-table.js, src/prop-types.js
#990
Adding ability to change overflowY setting
=> Ability to change overflowY on table

types/index.d.ts
=> string is not a column type

src/components/m-table-stepped-pagination.js, src/material-table.js
Relate the Github issue with this PR using `#1222`
Fixed showFirstLastPageButtons to work on stepped Pagination
#1222
branch | PR
*
=> Fix show first last page buttons stepped pagination

src/components/m-table-action.js
handleOnClick is equal to event => handleOnClick(event ).
This removes the redundant function generation.
=> Remove redundant function generation

types/index.d.ts
#725
This PR will update the type file for newly added field searchText in Options
=> Adding Types for searchText for options

demo/demo.js, src/components/m-table-toolbar.js, src/material-table.js
#1334
Moved searchText state to Toolbar component (still executing onSearchChangeDebounce in parent).
* Toolbar,
* Search
=> Search optimization fixes

demo/demo.js, src/components/m-table-filter-row.js
#1246 
Localization for FilterPlaceHolder
*
Hi, I've created a function that fetches the localization object as it is also used by multiple functions Please let me know if you have any issues with it. Also, I included the demo file so enhancement will be seen.
=> Enhancement: Filter Placeholder Localization

src/components/m-table-toolbar.js, src/default-props.js, src/material-table.js, src/prop-types.js, types/index.d.ts
https://github.com/mbrn/material-table/issues/1048
This PR adds a possibility to set autoFocus on search input.
=> Added searchAutoFocus to options

src/default-props.js, src/prop-types.js
#990 
Add correct typings for overflowY
=> Fix Typings with OverflowY

src/components/m-table-header.js
=> remove unused variable

src/components/m-table-edit-row.js
This PR adds the possibility to press escape to cancle an edit
* Edit Row
=> Cancle with Escape

src/components/m-table-pagination.js
#1386 
Resolve issue where pagination labelDisplayedRows displays '1-0 of 0' with empty results / zero count.
=> Resolve pagination count issue with empty results

README.md
N/A
Simplify dependency installation command
N/A
* N/A
=> simplify installation command

src/components/m-table-cell.js, types/index.d.ts
Currently there is no option to customize date formatting, this simple change adds dateFormatting property similar to currencyFormatting to format date/datetime
* MTableCell
=> add support for the date localization

.github/ROADMAP.md, README.md
Adding roadmap per our discussion @mbrn
=> Add Roadmap

src/material-table.js
#1969
This will prevent to call editable, if it is not defined
* material-table
=> fixes #1969

package.json, src/components/m-table-toolbar.js, src/material-table.js
None exactly.  I needed this functionality for another project and thought that it may be useful as a general feature.
This branch incorporates a new export option into the existing export menu that supports PDFs.  The exportPDF option utilizes the existing properties structure so that you can exportAllData and also override the export PDF function.
None.
* Header
* Toolbar
* Table?
I haven't contributed anything to this project before.  I searched for a contributing guide, but I could not find it.  I can fix whatever is needed to meet your standards.  Honestly, I wasn't sure if it would be better to have custom export options for overriding, but I didn't think there would be that many different types of exports to make …
=> Add function for exporting table as PDF in addition to the CSV option.

package.json
version 1.63.0 will fail with "jspdf" not found.
| other_pr_production | [link]() |
| other_pr_master     | [link]() |
\*
=> Move modules from dev dependencies to dependencies

src/components/m-table-cell.js, src/components/m-table-edit-field.js
This adds the error state to the select edit field
#1998
Also fixes #2142
=> Error state for select

demo/demo.js, src/components/m-table-cell.js, src/components/m-table-edit-row.js, src/components/m-table-toolbar.js, types/index.d.ts
#2144 
Fixes the validate disabling of the save button for strings correctly.
=> Fix for validate with string

types/index.d.ts
EditComponentProps had the wrong error defined in the interface.
=> fix: Fixed EditComponentProps

src/components/m-table-edit-field.js
This PR fixes the validation for the boolean check boxes by proving a FormGroup to display an error text.
=> Fix for boolean validation

src/utils/data-manager.js
| other_pr_production | [link]() |
| other_pr_master     | [link]() |
\*
A very simple change, which help us define whether we sort of table desc. It helps in our customSort(more control and possibilities), e.g to me help me define different behavior for desc and asc sort empty data cell, I wanted that are always on end sort.
=> Add Info attribute about desc sort for customSort

types/index.d.ts
| other_pr_production | [link]() |
| other_pr_master     | [link]() |
\*
=> Corrected ColumnDef type for typescript error.

types/index.d.ts
The changes parameter of onBulkUpdate is an object not an array.
=> Match onBulkUpdate changes types to real object

src/components/m-table-edit-row.js
Fixes #2269 #2304
Add onBulkEditRowChanged to the propTypes and provide default value;
N/A
EditComponent
=> Added default prop onBulkEditRowChanged;

src/components/m-table-body-row.js
N/A
Added way to style the line when another line is being edited using the rowStyle setting
N/A
MTableBodyRow
=> Added way to style the line when another line is being edited using the rowStyle setting

src/utils/data-manager.js
Fixes #2394
This trims the searchtext so that ' A' finds also A.
* Data-Manager
=> Trim search text
